version: '3.8'

services:
  app:
    image: ${IMAGE:-ghcr.io/joshshaloo/soccer/project-unify:develop}
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      DIRECT_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379
      NEXTAUTH_URL: https://preview.soccer-unify.com
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      EMAIL_SERVER_HOST: mailhog
      EMAIL_SERVER_PORT: 1025
      EMAIL_FROM: noreply@preview.soccer-unify.com
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - /mnt/truenas/docker_volumes/project-unity/preview/uploads:/app/uploads
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
    ports:
      - "3011:3000"
    depends_on:
      - postgres
      - redis
      - mailhog

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /mnt/truenas/docker_volumes/project-unity/preview/postgres:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - /mnt/truenas/docker_volumes/project-unity/preview/redis:/data
    deploy:
      replicas: 1

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8125:8025"  # Web UI
    deploy:
      replicas: 1

  n8n:
    image: n8nio/n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
      - N8N_HOST=n8n-preview.soccer-unify.com
      - N8N_WEBHOOK_URL=https://n8n-preview.soccer-unify.com
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_DATABASE=${N8N_DB_NAME}
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - /mnt/truenas/docker_volumes/project-unity/preview/n8n:/home/node/.n8n
    ports:
      - "5681:5678"

networks:
  default:
    driver: overlay
    attachable: true