// This file will be generated by Supabase CLI
// For now, using a placeholder type
export type Database = any

// After running `supabase gen types typescript`
// This will contain your full database schema types