#!/bin/bash

# Script to help set up Vercel environment variables
# This script provides the commands to run but doesn't execute them automatically

echo "==================================="
echo "Vercel Environment Variables Setup"
echo "==================================="
echo ""
echo "This script will guide you through setting up environment variables in Vercel."
echo ""
echo "Prerequisites:"
echo "1. Vercel CLI installed (npm i -g vercel)"
echo "2. Logged in to Vercel (vercel login)"
echo "3. Project linked (vercel link)"
echo ""
echo "Press Enter to continue..."
read

echo ""
echo "Run these commands to set up your environment variables:"
echo ""
echo "# Supabase Configuration"
echo "vercel env add NEXT_PUBLIC_SUPABASE_URL production"
echo "vercel env add NEXT_PUBLIC_SUPABASE_ANON_KEY production"
echo ""
echo "# Database Configuration"
echo "vercel env add DATABASE_URL production"
echo "vercel env add DIRECT_URL production"
echo ""
echo "# App Configuration"
echo "vercel env add NEXT_PUBLIC_APP_URL production"
echo ""
echo "# Optional: YouTube API"
echo "# vercel env add NEXT_PUBLIC_YOUTUBE_API_KEY production"
echo ""
echo "==================================="
echo "Example values to use:"
echo "==================================="
echo ""
echo "NEXT_PUBLIC_SUPABASE_URL: https://ouakhbtaifurigsjdnpt.supabase.co"
echo "NEXT_PUBLIC_SUPABASE_ANON_KEY: [Get from Supabase Dashboard > Settings > API]"
echo "DATABASE_URL: postgresql://postgres.[ref]:[password]@aws-0-us-west-1.pooler.supabase.com:6543/postgres?pgbouncer=true"
echo "DIRECT_URL: postgresql://postgres.[ref]:[password]@aws-0-us-west-1.pooler.supabase.com:5432/postgres"
echo "NEXT_PUBLIC_APP_URL: https://your-app.vercel.app"
echo ""
echo "==================================="
echo "To set for all environments at once:"
echo "==================================="
echo ""
echo "vercel env add [VARIABLE_NAME]"
echo "Then select: Production, Preview, Development"
echo ""
echo "==================================="
echo "To verify your setup:"
echo "==================================="
echo ""
echo "vercel env ls"
echo ""
echo "==================================="
echo "Important Reminders:"
echo "==================================="
echo ""
echo "1. Update Supabase Auth redirect URLs to include:"
echo "   - https://your-app.vercel.app/auth/callback"
echo "   - https://*.vercel.app/auth/callback"
echo ""
echo "2. Make sure to URL-encode database passwords if they contain special characters"
echo ""
echo "3. After setting variables, trigger a new deployment:"
echo "   vercel --prod"
echo ""